#cloud-config

fqdn: homelab-hole.homelab.home.arpa

users:
  - name: ${user_name}
    uid: 5001
    # gid does not exist
    groups: users,wheel
    lock_passwd: false
    plain_text_passwd: ${user_password}
    ssh_authorized_keys:
      - ${ssh_pubkey}
    sudo: ALL=(ALL) NOPASSWD:ALL
write_files:
  - path: /etc/sysctl.d/98-swappiness.conf
    content: 'vm.swappiness = 1'
    owner: root:root
    permissions: '0644'
  - path: /etc/resolv.conf
    owner: root:root
    permissions: '0644'
    content: |
      nameserver 80.67.169.12
      nameserver 80.67.169.40
  - path: /etc/network/interfaces
    owner: root:root
    permissions: '0644'
    content: |
      auto lo
      iface lo inet loopback

      auto eth0
        iface eth0 inet static
        address 10.99.99.3
        netmask 255.255.255.0
        gateway 10.99.99.2
  - path: /etc/containers/pihole.env
    content: |
      TZ=Etc/UTC
      WEBPASSWORD=password
      PIHOLE_DNS_=80.67.169.12;80.67.169.40
    owner: root:root
    permissions: '0644'

packages:
  - bash-completion
  - rsync
  - sudo
  - tmux
  - podman
  - vim
  - tcpdump

runcmd:
  - sysctl -p /etc/sysctl.d/98-swappiness.conf
  - rc-service networking restart
  - rc-update add cgroups
  - rc-update add podman
  - rc-service cgroups start
  - podman run -d --privileged --name pihole --env-file=/etc/containers/pihole.env -p 53:53/tcp -p 53:53/udp -p 80:80 --network=host -v etc-pihole:/etc/pihole --restart=always --hostname homelab-hole pihole/pihole:latest


final_message: "homelab-hole is ready for action !"
